### ISSUE TITLE
category selection does not reset when user goes from products page to home page and clicks on a new category.

### ISSUE THREAD

**Issue by TejasShekar** [ravikumar0403/furnishify-client#12]
https://github.com/ravikumar0403/furnishify-client/blob/d7a9a6ebbc02742ada6222ebbe511cbcea511e60/src/components/Filters.js#L10

How to reproduce the issue :
- In homepage, scroll down to categories section and select on a category, say 'desk' for example. It will redirect to products page with desk category selected.
- Now, go back to homepage and click on a different catgeory, say 'chair' for example. It will redirect to products page, but with both chain and desk categories selected.
- This issue persists when you again go back to homepage and select the remaining categories. It will redirect to product page with select category + previously selected catgeories.

**Comment by ravikumar0403** [comment]
Thank you for bringing this to my notice. I'll fix this soon
